In [1]:
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt

In [20]:
data1=sio.loadmat('chapter1/data1.mat')
data2=sio.loadmat('chapter1/data2.mat')
data3=sio.loadmat('chapter1/data3.mat')
data4=sio.loadmat('chapter1/data4.mat')

In [21]:
c1=data1['c1']
c2=data2['c2']
c3=data3['c3']
c4=data4['c4']

In [22]:
data=np.concatenate((c1,c2,c3,c4),axis=0)

In [91]:
rows,cols=data.shape
input_data=data[:,1:]
output_data1=data[:,0]

In [92]:
output_data=np.zeros((rows,4))

In [93]:
for i in range(1,5):
    output_data[output_data1==i,i-1]=1

In [94]:
def mapmaxmin(data):
    min_data=data.min(axis=0)
    max_data=data.max(axis=0)
    return (data-min_data)/(max_data-min_data),np.array([max_data,min_data])

In [96]:
np.random.seed(1000)
k=np.random.choice(range(input_data.shape[0]),2000,replace=False)

In [97]:
max(k)

1999

In [98]:
input_train=input_data[k[:1500],:]
output_train=output_data[k[:1500],:]
input_test=input_data[k[1500:],:]
output_test=output_data[k[1500:],:]

In [99]:
inputn,inputps=mapmaxmin(input_train)

In [100]:
input_data.shape

(2000, 24)

In [130]:
# 网络结构
innum=24
midnum=25
outnum=4
# 权值权重阀值初始化
w1=np.random.rand(innum,midnum)
b1=np.random.rand(1,midnum)
w2=np.random.rand(midnum,outnum)
b2=np.random.rand(1,outnum)

In [118]:
my_fun=lambda x:1/(1+np.exp(-x))

In [156]:
xite=1
Err=np.zeros(20)
for ii in range(20):
    for i in range(len(inputn)):
        I=np.dot(inputn[i,:],w1)+b1
        Iout=my_fun(I)
        yn=np.dot(Iout,w2)+b2
        e=output_train[i,:]-yn
        Err[ii]+=e.sum()
        # 计算w2,b2调整量
        dw2=np.dot(np.transpose(Iout),e)
        db2=e
        # 计算w1,b1调整量
        FI=Iout*(1-Iout)
        dw1=np.dot(np.transpose(inputn[i:i+1,:]),FI*np.dot(e,np.transpose(w2)))
        db1=FI*np.dot(e,np.transpose(w2))
        
        # 权值更新
        w1+=xite*dw1
        w2+=xite*dw2
        b1+=xite*db1
        b2+=xite*db2

D:\Program Files (x86)\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


In [157]:
Err

array([  4.13329937e-01,  -1.17623229e-15,  -1.17622908e-15,
        -1.17622587e-15,  -1.17622266e-15,  -1.17621946e-15,
        -1.17621625e-15,  -1.17621304e-15,  -1.17620983e-15,
        -1.17620662e-15,  -1.17620341e-15,  -1.17620020e-15,
        -1.17619699e-15,  -1.17619379e-15,  -1.17619058e-15,
        -1.17618737e-15,  -1.17618416e-15,  -1.17618095e-15,
        -1.17617774e-15,  -1.17617453e-15])

In [133]:
Iout

array([[ 0.99894176,  0.99895937,  0.99967725,  0.99960943,  0.99909327,
         0.99887353,  0.99867128,  0.99914547,  0.99935275,  0.99472813,
         0.99872127,  0.99868074,  0.9994224 ,  0.99821339,  0.99969478,
         0.99851727,  0.9996198 ,  0.99888456,  0.99919901,  0.99868048,
         0.99966417,  0.99876227,  0.99852346,  0.99904687,  0.99935496]])

In [121]:
w2.shape

(25, 4)

In [126]:
(np.dot(inputn[i:i+1,:],w1)+b1).shape

(25, 25)

In [127]:
np.dot(inputn[i:i+1,:],w1).shape

(1, 25)

In [135]:
yn.shape

(1, 4)

In [137]:
dw2.shape

(25, 4)

In [139]:
FI.shape

(1, 25)

In [141]:
np.dot(w2,e)

ValueError: shapes (25,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [143]:
e.shape

(1, 4)

In [145]:
w2.shape

(25, 4)

In [151]:
inputn[i,:].shape

(24,)

In [154]:
inputn[0:1,:]

array([[ 0.12499442,  0.37817689,  0.58771895,  0.72021943,  0.667838  ,
         0.63613138,  0.60847239,  0.47111636,  0.30970496,  0.69492276,
         0.48345823,  0.84910078,  0.51419104,  0.55892158,  0.62332326,
         0.65172065,  0.56470219,  0.35163639,  0.34080758,  0.51828084,
         0.71474425,  0.57020403,  0.51224878,  0.7721796 ]])

In [ ]:
np.array((1,2))