In [1]:
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt

In [2]:
data1=sio.loadmat('chapter1/data1.mat')
data2=sio.loadmat('chapter1/data2.mat')
data3=sio.loadmat('chapter1/data3.mat')
data4=sio.loadmat('chapter1/data4.mat')

In [3]:
c1=data1['c1']
c2=data2['c2']
c3=data3['c3']
c4=data4['c4']

In [4]:
data=np.concatenate((c1,c2,c3,c4),axis=0)

In [5]:
rows,cols=data.shape
input_data=data[:,1:]
output_data1=data[:,0]

In [6]:
output_data=np.zeros((rows,4))

In [7]:
for i in range(1,5):
    output_data[output_data1==i,i-1]=1

In [8]:
def mapmaxmin(data):
    min_data=data.min(axis=0)
    max_data=data.max(axis=0)
    return (data-min_data)/(max_data-min_data),np.array([max_data,min_data])

In [9]:
np.random.seed(1000)
k=np.random.choice(range(input_data.shape[0]),2000,replace=False)

In [97]:
max(k)

1999

In [10]:
input_train=input_data[k[:1500],:]
output_train=output_data[k[:1500],:]
input_test=input_data[k[1500:],:]
output_test=output_data[k[1500:],:]

In [11]:
inputn,inputps=mapmaxmin(input_train)

In [12]:
input_data.shape

(2000, 24)

In [176]:
# 网络结构
innum=24
midnum=25
outnum=4
# 权值权重阀值初始化
w1=np.random.rand(innum,midnum)*2-1
b1=np.random.rand(1,midnum)*2-1
w2=np.random.rand(midnum,outnum)*2-1
b2=np.random.rand(1,outnum)*2-1

In [177]:
my_fun=lambda x:1/(1+np.exp(-x))

In [178]:
xite=0.5
Err=np.zeros(20)
for ii in range(len(Err)):
    for i in range(len(inputn)):
        I=np.dot(inputn[i,:],w1)-b1
        Iout=my_fun(I)
        yn=np.dot(Iout,w2)-b2
        e=output_train[i,:]-yn
        Err[ii]+=np.abs(e).sum()
        # 计算w2,b2调整量
        dw2=np.dot(np.transpose(Iout),e)
        db2=e
        # 计算w1,b1调整量
        FI=Iout*(1-Iout)
        dw1=np.dot(np.transpose(inputn[i:i+1,:]),FI*np.dot(e,np.transpose(w2)))
        db1=FI*np.dot(e,np.transpose(w2))
        
        # 权值更新
        w1+=xite*dw1
        w2+=xite*dw2
        b1+=xite*db1
        b2+=xite*db2

In [179]:
inputn_test=(input_test-inputps[1,:])/(inputps[0,:]-inputps[1,:])

In [180]:
I=np.dot(inputn_test,w1)-b1
Iout=my_fun(I)
fore=np.dot(Iout,w2)-b2

In [181]:
output_fore=fore.max(axis=1)
output_fore=np.reshape(output_fore,(len(output_fore),1))

In [189]:
right_data=np.where(output_test-np.equal(fore,output_fore)[1]<0,False,output_test-np.equal(fore,output_fore)[1])
(len(right_data)-right_data.sum(axis=0))/len(right_data)

array([ 0.754,  0.742,  1.   ,  0.752])

In [168]:
output_data1[1500:]

array([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4

In [36]:
output_test

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [62]:
np.dot(Iout,w2)

array([[  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206],
       [  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206],
       [  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206],
       ..., 
       [  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206],
       [  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206],
       [  5178292.89251794,  10180386.50769143,    319690.25880034,
          4389999.32042206]])

In [80]:
w2

array([[ -3.45227092e+00,  -3.73983827e+00,  -3.96303939e+00,
         -4.92644402e+00],
       [ -1.03464646e+01,  -1.26991446e+01,  -1.30137274e+01,
         -1.53073810e+01],
       [  1.71237966e+01,   2.01503065e+01,   2.06119096e+01,
          2.39063607e+01],
       [  1.44259127e+01,   1.76539084e+01,   1.74095695e+01,
          2.12152490e+01],
       [ -2.86723776e+01,  -3.38331775e+01,  -3.42146758e+01,
         -4.11020058e+01],
       [ -3.26050164e+01,  -3.77536864e+01,  -3.85216906e+01,
         -4.60271110e+01],
       [  1.67825432e+01,   1.93514685e+01,   2.06328425e+01,
          2.44785200e+01],
       [  1.67912522e+01,   1.93988538e+01,   1.94786000e+01,
          2.35858935e+01],
       [  1.63166943e+01,   1.98188937e+01,   1.98302922e+01,
          2.42088582e+01],
       [ -8.28483942e+00,  -9.46766279e+00,  -9.97634638e+00,
         -1.22798605e+01],
       [  1.04614728e+01,   1.34313039e+01,   1.35748087e+01,
          1.61521094e+01],
       [  2.23707308e

In [184]:
Iout

array([[  7.61008429e-03,   6.20721473e-03,   6.98311663e-03, ...,
          1.29526356e-03,   1.15269214e-03,   3.20231510e-05],
       [  1.15275048e-02,   1.24660473e-02,   2.87810229e-02, ...,
          1.88414671e-03,   1.46730007e-03,   6.02686051e-05],
       [  2.35544987e-02,   1.61899418e-02,   1.25228372e-01, ...,
          2.06008792e-03,   1.52463876e-03,   5.93225924e-05],
       ..., 
       [  9.26009998e-03,   8.52777848e-03,   4.92743535e-03, ...,
          2.19497575e-03,   1.27609051e-03,   4.10167844e-05],
       [  1.93065722e-02,   1.37751076e-02,   1.58398140e-02, ...,
          3.11098777e-03,   2.40672248e-03,   7.08181519e-05],
       [  5.85737917e-03,   6.07032304e-03,   1.34342360e-02, ...,
          1.83196264e-03,   2.13800214e-03,   4.05748795e-05]])

In [161]:
output_fore.shape

(500,)